version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: notes-app-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: notesdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - notes-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-app-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/notesdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - notes-network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-app-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - notes-network

volumes:
  mongodb_data:

networks:
  notes-network:
    driver: bridge
